on:
  push:
    branches:
    - master
    
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v2.3.4
      - name: Doxygenize
        # You may pin to the exact commit or the version.
        # uses: langroodi/doxygenize@542946a13bc9021f5ba07c8751e6ab3d84bca154
        uses: langroodi/doxygenize@v1.7.0
        with:
          # Doxygen configuration file path
          doxygenconf: Doxygen/Doxyfile # default is ./Doxyfile
          # Generated HTML documents output folder
          htmloutput: docs
          # GitHub Pages branch name
          ghpagesbranch: gh-pages
          # GitHub Pages directory path
          ghpagesdir: docs
          # Toggle dark mode CSS
          
